name: Compile Assets

on:
  push:
    branches:
      - '3.x'
      - main
    paths:
      - 'resources/**'
      - 'package.json'
      - 'vite.config.js'

jobs:
  compile-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore: compile assets'
          commit-message: 'chore: automatic assets compilation'
          labels: automerge
          branch: auto/compile-assets
