name: Coverage

on:
  push:
    branches:
      - '3.x'
      - main
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: pcov

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Composer dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction

      - name: Install NPM dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Run tests for coverage
        run: php -d pcov.enabled=1 ./vendor/bin/pest --coverage --coverage-clover=coverage.xml --min=0

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
